export const FETCH_USER = 'FETCH_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const FETCH_ALL_PETS = 'FETCH_ALL_PETS';
export const RECEIVE_ALL_PETS = 'RECEIVE_ALL_PETS';

export const FETCH_PET= 'FETCH_PET';
export const RECEIVE_PET= 'RECEIVE_PET';

export const OPEN_CONFIRMATION_DIALOG = 'OPEN_CONFIRMATION_DIALOG';
export const CLOSE_CONFIRMATION_DIALOG = 'CLOSE_CONFIRMATION_DIALOG';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOG_OUT = 'LOG_OUT';
